FROM python:3.9

WORKDIR /app

COPY dashboard.py .

RUN pip install flask
RUN pip install matplotlib
RUN pip install scikit-learn
RUN pip install numpy
RUN pip install pandas
RUN pip install seaborn
RUN pip install psycopg2-binary

CMD ["python", "dashboard.py"]
